import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import "./globals.scss";
import { Header, WorkersWidget } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex justify-center w-full">
          <div className="max-w-screen-xl w-full">
            <Header />
            <div className="lg:container mx-auto px-10 mb-8 lg:flex lg:flex-row-reverse">
              <div className="lg:col-span-4 col-span-1">
                <div className="lg:sticky lg:relative lg:top-8">
                  <WorkersWidget />
                </div>
              </div>
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
